version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/gosell/gosell-js-library
    overwrite: yes
hooks:
  BeforeInstall:
    - location: scripts/before-installation.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/start-server.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start-server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop-server.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/test-server.sh
      timeout: 300
      runas: root
