version: "3.1"

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/staging-ssl.conf:/etc/nginx/conf.d/default.conf
      - /etc/nginx/ssl/jslib-staging-payments-tap-company_bckup.crt:/etc/nginx/jslib-staging-payments-tap-company.crt
      - /etc/nginx/ssl/jslib-staging-payments-tap-company.key:/etc/nginx/jslib-staging-payments-tap-company.key
      # - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      # - ./nginx/default-ssl.conf:/etc/nginx/conf.d/default.conf
      # - /etc/nginx/ssl/jslib.payments.gosell.io.chained.crt:/etc/nginx/jslib.payments.gosell.io.chained.crt
      # - /etc/nginx/ssl/jslib.payments.gosell.io.key:/etc/nginx/jslib.payments.gosell.io.key
    networks:
      - docker-network
    depends_on:
      - nodejs

  nodejs:
    build: .
    image: tap/gosell:v3
    ports:
      - "3000:3000"
      - "8000:8000"
    volumes:
      - ./demo:/app/demo
    environment:
      NODE_ENV: production
    restart: always
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge
