version: "3.1"

services:
  nginx:
    container_name: "${APP_NAME}-reverseproxy"
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      # - ./dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
      # - /docker-volumes/etc/letsencrypt/live/ohhaithere.com/fullchain.pem:/etc/letsencrypt/live/ohhaithere.com/fullchain.pem
      # - /docker-volumes/etc/letsencrypt/live/ohhaithere.com/privkey.pem:/etc/letsencrypt/live/ohhaithere.com/privkey.pem
    networks:
      - docker-network
    depends_on:
      - nodejs

  nodejs:
    build: .
    container_name: "tap-${APP_NAME}-${APP_VERSION}"
    image: hub.docker.tap.company/tap/${APP_NAME}:${APP_VERSION}
    ports:
      - "3000:3000"
      - "8000:8000"
    environment:
      NODE_ENV: production
    restart: always
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge
